# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises.

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)
print(A)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [3]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)


2
(3, 5)
15
int32


### Do the following computations on the matrices B and C:
* Elementwise subtraction.
* Elementwise multiplication.
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2
D = np.subtract(B, C)
E = np.multiply(B, C)
F = np.matmul(B, C)

print(B)
print(f'{C} \n ')

print(f'Subtraction \n {D}\n ')
print(f'Multiplication \n {E}\n ')
print(f'Matrix multiplication \n {F}\n ')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]] 
 
Subtraction 
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
 
Multiplication 
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
 
Matrix multiplication 
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]
 


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix.
* Calculcate the minimum value in each row.
* Calculcate the minimum value in each column.


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column.
* Calculate the median for each column.

In [5]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
C = np.exp(B)
print(f'Exponential \n{C} \n')

D = np.min(B)
print(f'Minimum \n{D} \n')

E = np.min(B, 0)
print(f'Minimum in Columns \n{E} \n')

F = np.min(B, 1)
print(f'Minimum in Rows \n{F} \n')

G = np.argmin(B)
print(f'Index Val for min val in matrix \n{G} \n')

H = np.argmin(B, 1)
print(f'Index Val for min val in each row \n{H} \n')

I = np.sum(B)
print(f'Sum \n{I} \n')

J = np.mean(B)
print(f'Mean \n{J} \n')

K = np.median(B)
print(f'Median  \n{K} \n')


Exponential 
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] 

Minimum 
1 

Minimum in Columns 
[1 2 3] 

Minimum in Rows 
[1 4 7] 

Index Val for min val in matrix 
0 

Index Val for min val in each row 
[0 0 0] 

Sum 
45 

Mean 
5.0 

Median  
5.0 



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [7]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [8]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

Excerpt from numpy fundamentals on indexing: 
* Note that if one indexes a multidimensional array with fewer indices than dimensions, one gets a subdimensional array.

Meaning that it will return a subarray of the rest of the values in the specified dimension, in this case an array with 5 values.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [9]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [11]:
for x in A:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean?

In [12]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


* First we create a range, a, essentially a list of numbers.
* Then we reshape it into a three dimensional array, b, using the reshape function. We basically ravel it into a list of numbers and then reorder it into a new array of the specified size and dimension. In this case (2, 3, -1).
This leads to an array with 2 dimensions of 3 axes each and -1 means that the number of elements in each axis will automatically fit the available data. In this case there are 5 elements in each axis. The number of elements must be divisable by 6 (for the 2 dimensions of 3 axes 2x3=6) othervise you get a value error.


In [13]:
a = np.arange(29)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

ValueError: cannot reshape array of size 29 into shape (2,3,newaxis)

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python.

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy.

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)
print(A[:])

[[1 2]
 [3 4]]
[2 2]
[[1 2]
 [3 4]]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [ ]:
def add_mult_matrices(x, y, operation):
    
        #print(x.shape) 
        #print(y.shape)
        
        is_good_matrix = False # Set high when both arrays are of the same size to allow addition
        allow_calc = False # Set high when the sizes conform
        is_scalar = False # Set high when x is a scalar 

        
        try:
                if isinstance(x, int) or isinstance(x, float):
                        is_scalar = True
        except AttributeError:
                pass
        
        try:
                if x.shape == y.shape: # matrices are of the same dimensions
                        is_good_matrix = True
        except AttributeError:
                pass
        
        
        if operation == 'add' and is_good_matrix:
                return np.add(x, y)
        
        if not is_scalar:
                if x.shape[1] == y.shape[0]:
                        allow_calc = True      
              
        if operation == 'multiply' and is_scalar:
                return np.multiply(x, y)
        elif operation == 'multiply' and allow_calc:
                return x @ y # can also use np.matmul(x, y) here, the @ operator casts to the matmul function
        else:
                return 'x columns and y rows must match or be one scalar and one array'
        
        
j = np.array([[2, 1, -1],
              [1, -1, 1]])

k = np.array([[4, 2],
              [-2, -4],
              [1, -2],
              [1, -2]])

print(np.shape(j))
print(np.shape(k))
print(add_mult_matrices(j ,k ,'multiply'))   


(2, 3)
(4, 2)
x columns and y rows must match or be one scalar and one array


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan".

In [ ]:
print('Uppgift: 10.1.1' )

x = np.array([4, 3])

print(f'a) {x.ndim}x{x.shape[0]}') # Or just: x.shape but then it assumes that the dimension is 1 so print is: (2, ) instead
print(f'b) {add_mult_matrices(5, x, 'multiply')}')

print(f'c) {add_mult_matrices(3, x, 'multiply')}')
print(f'd) {add_mult_matrices((add_mult_matrices(5, x, 'multiply')), add_mult_matrices(3, x, 'multiply'), 'add')}')

print(f'e) {add_mult_matrices(8, x, 'multiply')}')
print(f'f) {np.subtract(add_mult_matrices(4, x, 'multiply'), x)}')

print(f'g) {(x.reshape(2,-1).shape[0])}x{(x.reshape(2,-1).shape[1])}') # Or just use: x.reshape(2,-1).shape, But then the print format isn't as pretty
print(f'h) No, it is not defined since the vectors are of different dimensions')

y = np.power(x,2)
z  = np.sum(y)
print(f'i) {int(np.sqrt(z))} \n')



Uppgift: 10.1.1
a) 1x2
b) [20 15]
c) [12  9]
d) [32 24]
e) [32 24]
f) [12  9]
g) 2x1
h) No, it is not defined since the vectors are of different dimensions
i) 5 



In [ ]:
print('Uppgift: 10.1.2' )

v = np.array([[3],
             [7],
             [0],
             [11]])

print(f'a) {v.shape[0]}x{v.shape[1]} \n')
print(f'b) {add_mult_matrices(2, v, 'multiply')} \n')

print(f'c) {add_mult_matrices((add_mult_matrices(5, v, 'multiply')), add_mult_matrices(2, v, 'multiply'), 'add')} \n')
print(f'd) {np.subtract(add_mult_matrices(4, v, 'multiply'), add_mult_matrices(2, v, 'multiply'))}\n')

v_transpose = v.reshape(1, -1)
print(f'e) ≈ {(v_transpose.shape[0])}x{(v_transpose.shape[1])} \n')

y1 = np.power(v,2)
z1  = np.sum(y1)
print(f'f) ≈ {round(np.sqrt(z1), 2)} \n')



Uppgift: 10.1.2
a) 4x1 

b) [[ 6]
 [14]
 [ 0]
 [22]] 

c) [[21]
 [49]
 [ 0]
 [77]] 

d) [[ 6]
 [14]
 [ 0]
 [22]]

e) ≈ 1x4 

f) ≈ 13.38 



In [ ]:
print('Uppgift: 10.1.3 \n' )

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

y2 = np.power(v1,2)
z2  = np.sum(y2)
print(f'a) ≈ {round(np.sqrt(z2), 2)} \n')

v3 = np.subtract(v1, v2)
y3 = np.power(v3,2)
z3  = np.sum(y3)
print(f'b) ≈ {round(np.sqrt(z3), 2)} \n')


Uppgift: 10.1.3 

a) ≈ 7.14 

b) ≈ 4.47 



### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan".

In [ ]:
print('Uppgift: 10.1.3 \n' )

a = np.array([[2, 1, -1],
              [1, -1, 1]])

b = np.array([[4, -2, 1],
              [2, -4, -2]])

c = np.array([[1, 2],
              [2, 1]])

d = np.array([[3, 4],
              [4, 3]])

e = np.array([[1],
              [2]])

i = np.array([[1, 0],
              [0, 1]])

print(f'a) {add_mult_matrices(2, a, 'multiply')} \n')

print(f'b) {np.subtract(b, add_mult_matrices(2, a, 'multiply'))} \n')

print(f'c) Not defined since c and e have different dimensions\n')

print(f'd) {np.subtract(add_mult_matrices(2, d, 'multiply'), add_mult_matrices(3, c, 'multiply'))}\n')

d_transpsoe = np.transpose(d)
print(f'e) {add_mult_matrices(d_transpsoe, add_mult_matrices(2, d, 'multiply'), 'add')}\n') # In this case the transposition of d is equal to d, because of the shape of the matrix

#  2C⊤ − 2D⊤
two_ct = add_mult_matrices(2, np.transpose(c), 'multiply')
two_dt = add_mult_matrices(2, np.transpose(d), 'multiply')
print(f'f) {np.subtract(two_ct, two_dt)} \n')

print(f'g) Undefined since at and b are different dimensions\n')

print(f'h) {add_mult_matrices(a ,c ,'multiply')} \n')

print(f'i) {add_mult_matrices(c ,d ,'multiply')} \n')

print(f'j) {add_mult_matrices(c ,b ,'multiply')} \n')

print(f'k) {add_mult_matrices(c ,i ,'multiply')} \n')

print(f'k) {add_mult_matrices(a, np.transpose(b) ,'multiply')} \n')



Uppgift: 10.1.3 

a) [[ 4  2 -2]
 [ 2 -2  2]] 

b) [[ 0 -4  3]
 [ 0 -2 -4]] 

c) Not defined since c and e have different dimensions

d) [[3 2]
 [2 3]]

e) [[ 9 12]
 [12  9]]

f) [[-4 -4]
 [-4 -4]] 

g) Undefined since at and b are different dimensions

h) x columns and y rows must match or be one scalar and one array 

i) [[11 10]
 [10 11]] 

j) [[  8 -10  -3]
 [ 10  -8   0]] 

k) [[1 2]
 [2 1]] 

k) [[5 2]
 [7 4]] 



In [ ]:
print('Uppgift 10.2.2 \n')

a = np.array([[2, 3, 4],
              [5, 4, 1]])
print(f'a) {add_mult_matrices(a, np.transpose(a) ,'multiply')} \n')

Uppgift 10.2.2 

a) [[29 26]
 [26 42]] 



In [ ]:
print('Uppgift 10.2.3 \n')

a = np.array([[1, 2],
              [2, 4]])

b = np.array([[2, 1],
              [1, 3]])

c = np.array([[4, 3],
              [0, 2]])

x = add_mult_matrices(a, b ,'multiply')
y = add_mult_matrices(a, c ,'multiply')

print(f'{x} \n')
print(f'{y} \n')

print(f'AB = AC \n {x == y} \n')
print(f'B = C \n {b == c}')


Uppgift 10.2.3 

[[ 4  7]
 [ 8 14]] 

[[ 4  7]
 [ 8 14]] 

AB = AC 
 [[ True  True]
 [ True  True]] 

B = C 
 [[False False]
 [False False]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2, '\n')

# I can check if it is a view or a copy by changing data in v2 and checking if the data in v1 has changed.
# or I can use the base attribute on the arrays, it will return "none" for a copy
# From numpys guide on views and copies:
# "Views are created when elements can be addressed with offsets and strides in the original array. Hence, basic indexing always creates views."
# so  in this case we have created a view and any changes I do to v2 will reflect in v1

print(v1.base)
print(v2.base, '\n')

v2[-1] = 123
print(v1)
print(v2)

[0 1 2 3]
[2 3] 

None
[0 1 2 3] 

[  0   1   2 123]
[  2 123]


# And of course I could simply have read the next cell and realised that it was simply information about copies/and views and not a task to solve. Oh Well...

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)


None
[0 1 2 3]


In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
